services:
- type: web
  name: php-service
  env: 'docker'
  buildCommand: 'docker build -t my-php-app .'
  startCommand: 'docker run -d -p 10000:80 my-php-app'
  envVars:
  - key: 'DATABASE_URL'
    fromDatabase:
      name: 'my-mysql'
      property: 'connectionString'
- type: pserv
  name: my-mysql
  env: 'docker'
  image: 'mysql:8.0'
  envVars:
  - key: MYSQL_ROOT_PASSWORD
    value: my-secret-pw
- type: web
  name: phpmyadmin-service
  env: 'docker'
  buildCommand: 'docker build -t my-phpmyadmin .'
  startCommand: 'docker run -d --link my-mysql:db -p 10001:80 phpmyadmin/phpmyadmin'
